#!/bin/sh
mvn install:install-file -Dfile=xml-apis-1.4.01.jar -DgroupId=xml-apis -DartifactId=xml-apis -Dversion=1.4.01 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.ngdbc-1.0.0.jar -DgroupId=bizviz -DartifactId=com.ngdbc -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ojdbc14-10.2.0.1.0.jar -DgroupId=com.oracle -DartifactId=ojdbc14 -Dversion=10.2.0.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis-1.4.jar -DgroupId=org.apache.axis -DartifactId=axis -Dversion=1.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-adb-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-adb -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-adb-codegen-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-adb-codegen -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-ant-plugin-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-ant-plugin -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-clustering-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-clustering -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-codegen-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-codegen -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-fastinfoset-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-fastinfoset -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-java2wsdl-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-java2wsdl -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-jaxbri-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-jaxbri -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-jaxws-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-jaxws -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-jibx-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-jibx -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-json-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-json -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-kernel-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-kernel -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-metadata-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-metadata -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-mtompolicy-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-mtompolicy -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-saaj-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-saaj -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-soapmonitor-servlet-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-soapmonitor-servlet -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-spring-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-spring -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-transport-http-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-http -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-transport-local-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-local -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axis2-xmlbeans-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-xmlbeans -Dversion=1.6.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=activation-1.1.jar -DgroupId=javax.activation -DartifactId=activation -Dversion=1.1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ant-1.9.4.jar -DgroupId=org.apache.ant -DartifactId=ant -Dversion=1.9.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ant-antlr-1.9.4.jar -DgroupId=org.apache.ant -DartifactId=ant-antlr -Dversion=1.9.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ant-launcher-1.9.4.jar -DgroupId=org.apache.ant -DartifactId=ant-launcher -Dversion=1.9.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=antlr-2.7.7.jar -DgroupId=antlr -DartifactId=antlr -Dversion=2.7.7 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ant-nodeps-1.8.1.jar -DgroupId=org.apache.ant -DartifactId=ant-nodeps -Dversion=1.8.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=aopalliance-1.0.jar -DgroupId=aopalliance -DartifactId=aopalliance -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axiom-api-1.2.13.jar -DgroupId=org.apache.ws.commons.axiom -DartifactId=axiom-api -Dversion=1.2.13 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axiom-dom-1.2.13.jar -DgroupId=org.apache.ws.commons.axiom -DartifactId=axiom-dom -Dversion=1.2.13 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=axiom-impl-1.2.13.jar -DgroupId=org.apache.ws.commons.axiom -DartifactId=axiom-impl -Dversion=1.2.13 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=c3p0-0.9.1.jar -DgroupId=c3p0 -DartifactId=c3p0 -Dversion=0.9.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=codemodel-2.5.jar -DgroupId=com.sun.codemodel -DartifactId=codemodel -Dversion=2.5 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-cli-1.2.jar -DgroupId=commons-cli -DartifactId=commons-cli -Dversion=1.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-codec-1.3.jar -DgroupId=commons-codec -DartifactId=commons-codec -Dversion=1.10 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-collections-3.1.jar -DgroupId=commons-collections -DartifactId=commons-collections -Dversion=3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-email-1.1.jar -DgroupId=org.apache.commons -DartifactId=commons-email -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-fileupload-1.2.jar -DgroupId=commons-fileupload -DartifactId=commons-fileupload -Dversion=1.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-httpclient-3.1.jar -DgroupId=commons-httpclient -DartifactId=commons-httpclient -Dversion=3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-io-1.4.jar -DgroupId=commons-io -DartifactId=commons-io -Dversion=2.0.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-lang3-3.1.jar -DgroupId=org.apache.commons -DartifactId=commons-lang3 -Dversion=3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-logging-1.1.1.jar -DgroupId=commons-logging -DartifactId=commons-logging -Dversion=1.1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-validator-1.3.1.jar -DgroupId=commons-validator -DartifactId=commons-validator -Dversion=1.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=cors-filter-1.7.jar -DgroupId=com.thetransactioncompany -DartifactId=cors-filter -Dversion=1.7 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=cxf-bundle-2.7.11.jar -DgroupId=org.apache.cxf -DartifactId=cxf-bundle -Dversion=2.7.11 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=dom4j-1.6.1.jar -DgroupId=dom4j -DartifactId=dom4j -Dversion=1.6.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=dropbox-core-sdk-1.7.6.jar -DgroupId=com.dropbox.core -DartifactId=dropbox-core-sdk -Dversion=1.7.6 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=geronimo-stax-api_1.0_spec-1.0.1.jar -DgroupId=org.apache.geronimo.specs -DartifactId=geronimo-stax-api_1.0_spec -Dversion=1.0.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-api-client-1.17.0-rc.jar -DgroupId=com.google.api-client -DartifactId=google-api-client -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-api-client-java6-1.17.0-rc.jar -DgroupId=com.google.api-client -DartifactId=google-api-client-java6 -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-api-services-drive-v2-rev110-1.17.0-rc.jar -DgroupId=com.google.apis -DartifactId=google-api-services-drive -Dversion=v2-rev110-1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-collections-1.0.jar -DgroupId=com.google.collections -DartifactId=google-collections -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-gxp-0.2.4-beta.jar -DgroupId=com.google.gxp -DartifactId=google-gxp -Dversion=0.2.4-beta -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-http-client-1.17.0-rc.jar -DgroupId=com.google.http-client -DartifactId=google-http-client -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-http-client-jackson2-1.17.0-rc.jar -DgroupId=com.google.http-client -DartifactId=google-http-client-jackson2 -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-oauth-client-1.17.0-rc.jar -DgroupId=com.google.oauth-client -DartifactId=google-oauth-client -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=google-oauth-client-java6-1.17.0-rc.jar -DgroupId=com.google.oauth-client -DartifactId=google-oauth-client-java6 -Dversion=1.17.0-rc -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=gson-2.2.2.jar -DgroupId=com.google.code.gson -DartifactId=gson -Dversion=2.2.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=hadoop-core-1.1.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-core -Dversion=1.1.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=hibernate-core-3.6.0.Final.jar -DgroupId=org.hibernate -DartifactId=hibernate-core -Dversion=3.6.0.Final -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=hibernate-jpa-2.0-api-1.0.1.Final.jar -DgroupId=org.hibernate.javax.persistence -DartifactId=hibernate-jpa-2.0-api -Dversion=1.0.1.Final -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=hibernate-shards-1.1.0.jar -DgroupId=org.hibernate -DartifactId=hibernate-shards -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=httpcore-4.0.jar -DgroupId=org.apache.httpcomponents -DartifactId=httpcore -Dversion=4.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=commons-dbcp-1.4.jar -DgroupId=commons-dbcp -DartifactId=commons-dbcp -Dversion=1.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jersey-server-1.17.1.jar -DgroupId=com.sun.jersey -DartifactId=jersey-server -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jersey-core-1.17.1.jar -DgroupId=com.sun.jersey -DartifactId=jersey-core -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jersey-servlet-1.17.1.jar -DgroupId=com.sun.jersey -DartifactId=jersey-servlet -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jersey-json-1.17.1.jar -DgroupId=com.sun.jersey -DartifactId=jersey-json -Dversion=1.17.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jackson-mapper-asl-1.9.12.jar -DgroupId=org.codehaus.jackson -DartifactId=jackson-mapper-asl -Dversion=1.9.11 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jackson-core-asl-1.9.12.jar -DgroupId=org.codehaus.jackson -DartifactId=jackson-core-asl -Dversion=1.9.11 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jackson-core-2.2.3.jar -DgroupId=com.fasterxml.jackson.core -DartifactId=jackson-core -Dversion=2.2.3 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=java-property-utils-1.7.1.jar -DgroupId=com.thetransactioncompany -DartifactId=java-property-utils -Dversion=1.7.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=javassist-3.12.0.GA.jar -DgroupId=javassist -DartifactId=javassist -Dversion=3.12.0.GA -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=javax.servlet-api-3.0.1.jar -DgroupId=javax.servlet -DartifactId=javax.servlet-api -Dversion=3.0.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=javax.ws.rs-api-2.0-m10.jar -DgroupId=javax.ws.rs -DartifactId=javax.ws.rs-api -Dversion=2.0-m10 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jaxrpc-api-1.1.jar -DgroupId=javax.xml -DartifactId=jaxrpc -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jboss-logging-3.1.0.GA.jar -DgroupId=org.jboss.logging -DartifactId=jboss-logging -Dversion=3.1.0.GA -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jboss-transaction-api_1.1_spec-1.0.0.Final.jar -DgroupId=org.jboss.spec.javax.transaction -DartifactId=jboss-transaction-api_1.1_spec -Dversion=1.0.0.Final -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jcl-over-slf4j-1.7.5.jar -DgroupId=org.slf4j -DartifactId=jcl-over-slf4j -Dversion=1.7.5 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jdo2-api-2.3-eb.jar -DgroupId=javax.jdo -DartifactId=jdo2-api -Dversion=2.3-eb -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jdom-1.1.jar -DgroupId=jdom -DartifactId=jdom -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jdom2-2.0.5.jar -DgroupId=org.jdom -DartifactId=jdom2 -Dversion=2.0.5 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jira-javamelody-1.1.0.jar -DgroupId=javamelody -DartifactId=jira-javamelody -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jline-0.9.94.jar -DgroupId=jline -DartifactId=jline -Dversion=0.9.94 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jrobin-1.5.9.jar -DgroupId=org.jrobin -DartifactId=jrobin -Dversion=1.5.9 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=json-20090211.jar -DgroupId=org.json -DartifactId=json -Dversion=20090211 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=json-lib-2.4-jdk15.jar -DgroupId=net.sf.json-lib -DartifactId=json-lib -Dversion=2.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jta-1.1.jar -DgroupId=javax.transaction -DartifactId=jta -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=juli-6.0.18.jar -DgroupId=org.apache.tomcat -DartifactId=juli -Dversion=6.0.18 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=junit-4.12.jar -DgroupId=junit -DartifactId=junit -Dversion=4.12 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=lambdaj-1.1.0.jar -DgroupId=com.googlecode.lambdaj -DartifactId=lambdaj -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=libfb303-0.9.2.jar -DgroupId=org.apache.thrift -DartifactId=libfb303 -Dversion=0.9.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=log4j-1.2.17.jar -DgroupId=log4j -DartifactId=log4j -Dversion=1.2.17 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=geronimo-javamail_1.4_spec-1.6.jar -DgroupId=javax.mail -DartifactId=mail -Dversion=1.4 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=sqljdbc4-4-2.0.jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc4 -Dversion=4-2.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=neethi-3.0.2.jar -DgroupId=org.apache.neethi -DartifactId=neethi -Dversion=3.0.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ojdbc14-10.2.0.1.0.jar -DgroupId=com.oracle -DartifactId=ojdbc14 -Dversion=10.2.0.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=olap4j-1.2.0.jar -DgroupId=org.olap4j -DartifactId=olap4j -Dversion=1.2.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=olap4j-xmla-1.2.0.jar -DgroupId=org.olap4j -DartifactId=olap4j-xmla -Dversion=1.2.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xercesImpl-2.10.0.jar -DgroupId=xerces -DartifactId=xercesImpl -Dversion=2.10.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=oro-2.0.8.jar -DgroupId=oro -DartifactId=oro -Dversion=2.0.8 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=oval-1.31.jar -DgroupId=net.sf.oval -DartifactId=oval -Dversion=1.31 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=plexus-container-default-1.0-alpha-10.jar -DgroupId=org.codehaus.plexus -DartifactId=plexus-container-default -Dversion=1.0-alpha-10 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=plexus-utils-1.2.jar -DgroupId=org.codehaus.plexus -DartifactId=plexus-utils -Dversion=1.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=poi-3.10-FINAL.jar -DgroupId=org.apache.poi -DartifactId=poi -Dversion=3.10-FINAL -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=poi-excelant-3.10-FINAL.jar -DgroupId=org.apache.poi -DartifactId=poi-excelant -Dversion=3.10-FINAL -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=poi-ooxml-3.10-FINAL.jar -DgroupId=org.apache.poi -DartifactId=poi-ooxml -Dversion=3.10-FINAL -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=poi-ooxml-schemas-3.10-FINAL.jar -DgroupId=org.apache.poi -DartifactId=poi-ooxml-schemas -Dversion=3.10-FINAL -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=poi-scratchpad-3.10-FINAL.jar -DgroupId=org.apache.poi -DartifactId=poi-scratchpad -Dversion=3.10-FINAL -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=sitemesh-2.4.2.jar -DgroupId=opensymphony -DartifactId=sitemesh -Dversion=2.4.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=slf4j-api-1.7.5.jar -DgroupId=org.slf4j -DartifactId=slf4j-api -Dversion=1.7.5 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=slf4j-log4j12-1.7.5.jar -DgroupId=org.slf4j -DartifactId=slf4j-log4j12 -Dversion=1.7.5 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-aop-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-aop -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-beans-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-beans -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-context-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-context -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-core-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-core -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-expression-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-expression -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-jdbc-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-jdbc -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-orm-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-orm -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-tx-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-tx -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=spring-web-1.1.0.jar -DgroupId=org.springframework -DartifactId=spring-web -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=testng-5.1-jdk15.jar -DgroupId=org.testng -DartifactId=testng -Dversion=5.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=velocity-1.6.3.jar -DgroupId=org.apache.velocity -DartifactId=velocity -Dversion=1.6.3 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=woden-api-1.0M9.jar -DgroupId=org.apache.woden -DartifactId=woden-api -Dversion=1.0M9 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=woden-impl-commons-1.0M9.jar -DgroupId=org.apache.woden -DartifactId=woden-impl-commons -Dversion=1.0M9 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=woden-impl-dom-1.0M9.jar -DgroupId=org.apache.woden -DartifactId=woden-impl-dom -Dversion=1.0M9 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=force-wsc-23.0.0.jar -DgroupId=com.force.api -DartifactId=force-wsc -Dversion=23.0.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=wsdl4j-1.6.3.jar -DgroupId=wsdl4j -DartifactId=wsdl4j -Dversion=1.6.3 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xmlbeans-2.3.0.jar -DgroupId=org.apache.xmlbeans -DartifactId=xmlbeans -Dversion=2.3.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xmlpull-1.1.3.1.jar -DgroupId=xmlpull -DartifactId=xmlpull -Dversion=1.1.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=XmlSchema-1.4.7.jar -DgroupId=org.apache.ws.commons.schema -DartifactId=XmlSchema -Dversion=1.4.7 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xpp3_min-1.1.4c.jar -DgroupId=xpp3 -DartifactId=xpp3_min -Dversion=1.1.4c -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xstream-1.4.2.jar -DgroupId=com.thoughtworks.xstream -DartifactId=xstream -Dversion=1.4.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=struts2-core-2.2.1.jar -DgroupId=org.apache.struts -DartifactId=struts2-core -Dversion=2.2.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=quartz-2.2.1.jar -DgroupId=org.quartz-scheduler -DartifactId=quartz -Dversion=2.2.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=lucene-snowball-3.0.3.jar -DgroupId=org.apache.lucene -DartifactId=lucene-snowball -Dversion=3.0.3 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=neo4j-cypher-compiler-2.1-2.1.2.jar -DgroupId=org.neo4j -DartifactId=neo4j-cypher-compiler-2.1 -Dversion=2.1.2 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=dynamicreports-core-4.0.0.jar -DgroupId=net.sourceforge.dynamicreports -DartifactId=dynamicreports-core -Dversion=4.0.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=jxl-2.6.12.jar -DgroupId=net.sourceforge.jexcelapi -DartifactId=jxl -Dversion=2.6.12 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=json-simple-1.1.1.jar -DgroupId=com.googlecode.json-simple -DartifactId=json-simple -Dversion=1.1.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=braintree-java-2.46.0.jar -DgroupId=com.braintreepayments.gateway -DartifactId=braintree-java -Dversion=2.46.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=org.eclipse.persistence.moxy-2.5.0.jar -DgroupId=org.eclipse.persistence -DartifactId=org.eclipse.persistence.moxy -Dversion=2.5.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.bdbizviz.soapbuilder-2.0.0.jar -DgroupId=bizviz -DartifactId=com.bdbizviz.soapbuilder -Dversion=${project.version} -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.bdbizviz.bizvizconnector-2.0.0.jar -DgroupId=bizviz -DartifactId=com.bdbizviz.bizvizconnector -Dversion=${project.version} -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.bdbizviz.demo.textanalytics-2.0.0.jar -DgroupId=bizviz -DartifactId=com.bdbizviz.demo.textanalytics -Dversion=${project.version} -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.bdbizviz.mails-2.0.0.jar -DgroupId=bizviz -DartifactId=com.bdbizviz.mails -Dversion=${project.version} -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=com.bdbizviz.persistence.entities-2.0.0.jar -DgroupId=bizviz -DartifactId=com.bdbizviz.persistence.entities -Dversion=${project.version} -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=xwork-core-2.2.1.jar -DgroupId=org.apache.struts.xwork -DartifactId=xwork-core -Dversion=2.3.34 -Dpackaging=jar -DgeneratePom=true